apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-app
    env: prod
  name: python-app-76rl8
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32346
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: python-app
    env: prod
  sessionAffinity: None
  type: LoadBalancer